pipeline {
    agent any
    stages {
        stage('打包') {
            steps {
                //
                sh 'npm run build:test'
                sh 'chmod 777 docker/run.sh'
            }

        stage('构建docker镜像') {
            steps {
                sh 'docker/run.sh'
            }
        }
        stage('清理代码') {
                steps {
                    //
                    sh 'rm -rf * &&  rm -rf .git*'
                }
            }
        }
}
