pipeline {
    agent any
    stages {
        stage('编译&打包') {
            steps {
                //
                sh 'cnpm install'
                sh 'cnpm run build:test'
                sh 'chmod 777 docker/run.sh'
            }
        }
        stage('构建docker镜像') {
            steps {
                sh 'docker/run.sh'
            }
        }
        stage('清理代码') {
                steps {
                    //
                    sh 'rm -rf * &&  rm -rf .git* && rm -rf .env*'
                }
            }
        }
}
